version: '3'
services:
  api:
    build: .
    container_name: c3po-api
    working_dir: /app
    env_file: secrets.env
    environment:
      FLASK_APP: ./c3po/main.py
      DATABASE_URL: postgresql://postgres:postgres@db/postgres
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - 'db'

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
