version: '3'
services:
  api:
    build: .
    container_name: c3po-api
    working_dir: /app
    env_file: secrets.env
    command: [ "c3po_api.main:main()", "--certfile=./secrets/cert.pem", "-b 0.0.0.0:8443" ]
    environment:
      FLASK_APP: ./c3po_api/main.py
      DATABASE_URL: postgresql://postgres:postgres@db/postgres
    volumes:
      - ./:/app
    ports:
      - 1443:8443
    depends_on:
      - 'db'


  bot:
    build: .
    container_name: c3po-bot
    working_dir: /app
    env_file: secrets.env
    command: [ "c3po_bot.main:main()", "--certfile=./secrets/cert.pem", "-b 0.0.0.0:8443" ]
    environment:
      FLASK_APP: ./c3po_bot/main.py
    volumes:
      - ./:/app
    ports:
      - 2443:8443


  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
